version: "3.6"

services:
  app:
    build: ./
    container_name: gradle-app
    environment:
      - FIREBASE_SERVICE_ACCOUNT_ID='firebase-adminsdk-f1577@vtmconverter.iam.gserviceaccount.com'
    volumes:
      - ./:/gradleproject
    ports:
      - 8080:8080
    expose:
      - 8080